# This is a basic workflow to help you get started with Actions

name: Deploy test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the environment'
        type: choice
        options:
        - dev
        - qa
        - prod
        required: true
        default: dev

env:
  APP_NAME: 'asfa-tccc-cfa-${{ github.event.inputs.env }}-node-mktapi'    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Configure env
        id: publish-profile-selector
        run: |
          if ${{ github.event.inputs.env }} == "dev" (echo "::set-output name=publish_profile_secret::AZURE_SRV_PUBLISH_PROFILE_DEV")
      - name: Run a one-line script
        run: |
          echo APP_NAME: ${{env.APP_NAME}}
          echo ${{ secrets[steps.publish-profile-selector.outputs.publish_profile_secret] }}
